### ISSUE TITLE
FIX: No constraint tree needed for families with one ott

### ISSUE THREAD

**Issue by Naomivanes** [naturalis/barcode-constrained-phylogeny#41]
Raxml gives an error when a family alignment with only one ott is being used (multiple barcodes from the same ott).
Change raxml rule from shell command line to python script that checks if a constraint tree newick file is empty first. If so run raxml without constraint tree, else with a constraint tree.

**Comment by rvosa** [comment]
Technically this is also true for families with two otts. I think the thing to do is to write 0-byte files in those cases, so that Snakemake can see that the input files have been processed. Likewise probably also for raxml: the wrapper writes an empty output with the name that Snakemake expects so it thinks we're done with that {family}. The trick then comes when we need to sample for the backbone.

**Comment by Naomivanes** [comment]
Fixed for raxml, but might still be a problem when adding other things to the pipeline so will keep issue open.
